### ISSUE TITLE
handle userid and username differently

### ISSUE THREAD

**Issue by kulmann** [owncloud/ocis-ocs#64]
Chat excerpt from @butonic:

```
the provisioning api makes no difference between usernames and userids ... that is a new concept ...

that the userid generated by the account service happens to be a uuid, which happens to be hex should be opaque to the system.

could the provisioning api treat the incoming userid as the username?

userid in the provisioning api is actually a username.

if you compare ldap the userid in oc10 is sth like the entryuuid or the objectguid

just because the testsuite uses usernames as the userid does not mean that is the right thing to do

IMO the testsuite should use uuids for the userid. in ocis we added the username parameter to allow that.

to be backwards compatible we would have to make the ocs api use the userid as the username. we could try to allow setting userid and username: if a new user is created and username and userid are given we could treat them as is. but if only userid is given ... roll a uuid userid and use the given userid as the username. that might make old clients work ... but will make the testsuite ... well more complicated ...
```

**Comment by kulmann** [comment]
I would be fine with this. I.e. in ocis-ocs:
1. clear userid field in `create` request, so that the account service generates an internal id
2. in `delete`, `get` and `edit` requests, use the provided `userid` as username. That means that all three requests need to make a search query to the accounts service first, to obtain the internal id of the user, and then make the actual request.

Important: this is only actually OK if we never use the provisioning API in (2) with the actual internal id. That depends on the use cases. If there are no plans to support the provisioning API in oCIS with actual internal ids, then this would be ok. Otherwise we need to add the username as second param to the requests in (2).

Thoughts @phil-davis @butonic  ?

**Comment by phil-davis** [comment]
I agree. The problem seems to be just about naming.
https://doc.owncloud.com/server/admin_manual/configuration/user/user_provisioning_api.html

For example, the description for the arguments of "add user":
`userid  string  The required username for the new user.`

That API implementation has an argument with formal name `userid` that is commonly described with the word "username".

The OCIS "internal userid" is something that an external client does not need to process (and probably therefore does not need to even know). All requests to WebDav and OCS APIs by an external client use the thing that oC10 calls "userid or username".

Why does OCIS need to try to re-use the formal argument `userid` for the internal identifier?

OCIS can do what it likes to generate "internal random strings" for anything if they are just used internally and they are not exposed to clients.

If we want to allow "provisioning clients" to specify a value for a "bonus user identifier" when they create a user, then add that as a new optional argument when creating a user. Call it whatever we like, different to the existing argument names (don't call it `userid` or `password` or `email` or `displayname`...) - e.g. `bonus_user_identifier` (naming is hard - think of a name for this). Specify whatever rules we like for it (string, has to be unique, case sensitive...) And keep the existing rules for `userid` (which has a description "username", and is the "username" that real humans typically enter at a login page, and internally OCIS can use local variables `username` if it likes).

If we want clients to be able to optionally make WebDav and/or OCS requests that use `bonus_user_identifier` in place of `userid` ("username"), then that is an extension to the existing oC10 behavior, which can be advertised as a capability. Then we have to think about rules to prevent namespace collisions between `bonus_user_identifier` and `userid`.

**Comment by kulmann** [comment]
@phil-davis I changed what we discussed in https://github.com/owncloud/ocis/pull/619 and it blows up the test suite again. The home folder of the respective user is created from the internal account id. Which is not the provided `userid` anymore, but an internally generated uuid.
https://drone.owncloud.com/owncloud/ocis/98/13/7

**Comment by phil-davis** [comment]
Yes, for example the trashbin tests in that drone pipeline try to check if a file is in the trashbin. They do a PROPFIND... to get a listing of the trashbin, and try to search in the response. But the test will use an endpoint documented in https://doc.owncloud.com/server/developer_manual/webdav_api/trashbin.html - `remote.php/dav/trash-bin/<username>` and for compatibility with oC10 behaviour, OCIS needs to respond to `remote.php/dav/trash-bin/Alice` - whatever the "system administrator" set as the `userid` is what should work in end-point URLs, and be in a PROPFIND response etc.

External clients should not need to find out the "internal UUID" - that is just an internal data item that the back-end can decide to create and use if it wants to.

ownCloud clients (curl API requests, desktop, Android, iOS, Phoenix...) should not need to know that this "backend UUID" exists. The user logs in with the "user string" `Alice` (call it `userid` `username` whatever - naming is hard) and the client then expects to construct all API requests with `Alice` and that responses will mention `Alice` (not some internal UUID)

**Comment by kulmann** [comment]
New plan: in order to keep folder names with the ocs userIds in webdav and ocs responses, we need to:
- create accounts with userid interpreted as account_uuid
- delete, update and search accounts by their userids interpreted as usernames

**Comment by kulmann** [comment]
solved in https://github.com/owncloud/ocis/pull/709
